import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    );

    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth(); // 0-indexed

    // Billing period: 1st to last day of current month
    const periodStart = new Date(year, month, 1).toISOString().split("T")[0];
    const periodEnd = new Date(year, month + 1, 0).toISOString().split("T")[0];

    // Due date: 15th of current month
    const dueDate = new Date(year, month, 15).toISOString().split("T")[0];

    // Get all active clients with a monthly payment
    const { data: clients, error: clientsErr } = await supabase
      .from("clients")
      .select("id, client_name, company_name, monthly_payment")
      .eq("status", "active")
      .not("monthly_payment", "is", null)
      .gt("monthly_payment", 0);

    if (clientsErr) throw clientsErr;
    if (!clients || clients.length === 0) {
      return new Response(
        JSON.stringify({ message: "No active clients with payments", invoices: 0 }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    let created = 0;
    let skipped = 0;

    for (const client of clients) {
      // Check if invoice already exists for this period
      const { data: existing } = await supabase
        .from("invoices")
        .select("id")
        .eq("client_id", client.id)
        .eq("billing_period_start", periodStart)
        .eq("billing_period_end", periodEnd)
        .limit(1);

      if (existing && existing.length > 0) {
        skipped++;
        continue;
      }

      const amount = client.monthly_payment || 0;
      const tax = Math.round(amount * 0.18 * 100) / 100; // 18% GST

      const { error: insertErr } = await supabase.from("invoices").insert({
        invoice_number: "", // auto-generated by trigger
        client_id: client.id,
        amount,
        tax_amount: tax,
        total_amount: amount + tax,
        status: "draft",
        due_date: dueDate,
        billing_period_start: periodStart,
        billing_period_end: periodEnd,
        notes: `Monthly invoice for ${client.client_name}`,
      });

      if (insertErr) {
        console.error(`Failed to create invoice for ${client.client_name}:`, insertErr);
        continue;
      }
      created++;
    }

    // Log activity
    await supabase.from("activity_logs").insert({
      entity: "invoice",
      entity_id: "00000000-0000-0000-0000-000000000000",
      action: "bulk_generate",
      metadata: {
        created,
        skipped,
        total_clients: clients.length,
        period: `${periodStart} to ${periodEnd}`,
      },
    });

    console.log(`Invoice generation: ${created} created, ${skipped} skipped`);

    return new Response(
      JSON.stringify({ message: `Generated ${created} invoices`, created, skipped }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("generate-invoices error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
